version: '3.1'
services:
  eks-kubectl-docker:
    image: eks-kubectl-docker:latest
    tty: true
    environment:
      - AWS_REGION=${AWS_REGION}
      - CLUSTER_NAME=${CLUSTER_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}